### ISSUE TITLE
Inconsistent PyPI package version

### ISSUE THREAD

**Issue by attilaolah** [wichitacode/flask-compress#17]
Apparently PyPI shows [1.2.0] as the latest version, but the version number [in the download link][1.2.0.1] is [1.2.0.1]. As a result, `pip install Flask-Compress==1.2.0` doesn't work. As a result, packages defining `Flask-Compress==1.2.0` as a dependency fail to install.

On the other hand, while `pip install Flask-Compress==1.2.0.1` works, specifying `setup(install_requires=['Flask-Compress==1.2.0.1'], …)` in `setup.py` allows the package to be installed, but renders its `entry_points` (such as `console_scripts`) unusable, failing with this error:

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/myapp", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3060, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Flask-Compress==1.2.0.1' distribution was not found and is required by myapp
```

(example output from a console script named `myapp`, installed by a package with the same name).

Please fix the version number on PyPI. Probably the easiest thing would be to release a new version, either 1.2.0.2 or, preferably, 1.2.1.

[1.2.0]: https://pypi.python.org/pypi/Flask-Compress/1.2.0
[1.2.0.1]: https://pypi.python.org/packages/source/F/Flask-Compress/Flask-Compress-1.2.0.1.tar.gz

**Comment by libwilliam** [comment]
Dang, I was hoping that didn't happen. I will have it fixed within the hour. Sorry about that.

**Comment by attilaolah** [comment]
No worries, and no rush, I can live with `1.1.1` (which installs just fine) until this gets fixed.

Thanks! :bowtie:

**Comment by libwilliam** [comment]
I can't come up with a good way of fixing `1.2.0` but there is now a `1.2.1` that will work correctly. 

Thank you very much for reporting this!

**Comment by attilaolah** [comment]
Cool, let me wait for our CI results.

**Comment by attilaolah** [comment]
Wercker says `1.2.1` is good to go. Thank for the quick fix!
